"""
MkDocs hook: Auto-generate knowledge graph data from docs/ structure.
Runs on every build — scans all .md files for cross-references and
generates Cytoscape.js node/edge data automatically.
"""

import os
import re
import json
import logging

log = logging.getLogger("mkdocs.hooks.generate_graph")

DIR_TO_GROUP = {
    "topics": "core",
    "use-cases": "usecase",
    "rfcs": "rfc",
    "implementations": "impl",
    "labs": "impl",
}

SKIP_FILES = {"index.md", "tags.md", "knowledge-graph.md", "CNAME"}
SKIP_DIRS = {"assets", "community"}


def on_pre_build(config, **kwargs):
    docs_dir = config["docs_dir"]
    elements = []
    node_ids = set()
    file_to_id = {}

    # Pass 1: Discover pages → nodes
    for root, dirs, files in os.walk(docs_dir):
        rel_dir = os.path.relpath(root, docs_dir)
        top_dir = rel_dir.split(os.sep)[0] if rel_dir != "." else ""
        if top_dir in SKIP_DIRS:
            continue

        for fname in files:
            if fname in SKIP_FILES or not fname.endswith(".md"):
                continue

            filepath = os.path.join(root, fname)
            rel_path = os.path.relpath(filepath, docs_dir)
            group = DIR_TO_GROUP.get(top_dir, None)
            if group is None:
                continue

            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()

            title_match = re.search(r"^title:\s*(.+)$", content, re.MULTILINE)
            if not title_match:
                title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
            if not title_match:
                continue

            title = re.sub(r":[a-z-]+:", "", title_match.group(1)).strip()
            node_id = fname.replace(".md", "").replace("-", "_")
            url_path = rel_path.replace(".md", "/").replace(os.sep, "/")

            elements.append({
                "data": {"id": node_id, "label": title, "group": group, "url": url_path}
            })
            node_ids.add(node_id)
            file_to_id[rel_path] = node_id

    # Pass 2: Discover links → edges
    seen_links = set()
    for root, dirs, files in os.walk(docs_dir):
        rel_dir = os.path.relpath(root, docs_dir)
        top_dir = rel_dir.split(os.sep)[0] if rel_dir != "." else ""
        if top_dir in SKIP_DIRS:
            continue

        for fname in files:
            if fname in SKIP_FILES or not fname.endswith(".md"):
                continue

            filepath = os.path.join(root, fname)
            rel_path = os.path.relpath(filepath, docs_dir)
            source_id = file_to_id.get(rel_path)
            if not source_id:
                continue

            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()

            for link_target in re.findall(r"\[[^\]]*\]\(([^)]+\.md)\)", content):
                resolved = os.path.normpath(
                    os.path.join(os.path.dirname(rel_path), link_target)
                )
                target_id = file_to_id.get(resolved)
                if target_id and target_id != source_id:
                    link_key = tuple(sorted([source_id, target_id]))
                    if link_key not in seen_links:
                        seen_links.add(link_key)
                        elements.append({
                            "data": {"source": source_id, "target": target_id}
                        })

    node_count = len([e for e in elements if "source" not in e["data"]])
    edge_count = len([e for e in elements if "source" in e["data"]])

    js_content = f"""// AUTO-GENERATED by hooks/generate_graph.py — DO NOT EDIT MANUALLY
// {node_count} nodes, {edge_count} edges

;(function() {{
const GRAPH_ELEMENTS = {json.dumps(elements)};

const GROUP_COLORS = {{core:"#ab47bc",usecase:"#5c6bc0",rfc:"#66bb6a",impl:"#ff9800"}};
const GROUP_NAMES = {{core:"Topics",usecase:"Use Cases",rfc:"RFCs",impl:"Implementations"}};

const activeGroups = new Set(["core","usecase","rfc","impl"]);

function initKnowledgeGraph() {{
  const container = document.getElementById("graph-container");
  if (!container || container.dataset.init) return;
  container.dataset.init = "1";

  const cy = window._graphCy = cytoscape({{
    container: container,
    elements: GRAPH_ELEMENTS,
    style: [
      {{
        selector: "node",
        style: {{
          "label": "data(label)",
          "text-wrap": "wrap",
          "text-max-width": "80px",
          "font-size": "9px",
          "font-weight": "500",
          "color": "#e8e6f0",
          "text-valign": "center",
          "text-halign": "center",
          "background-opacity": 0.15,
          "border-width": 2,
          "border-opacity": 0.8,
          "width": 55,
          "height": 55,
          "text-outline-color": "#0a0a18",
          "text-outline-width": 2,
        }}
      }},
      {{
        selector: "node[group='core']",
        style: {{ "background-color": "#ab47bc", "border-color": "#ab47bc" }}
      }},
      {{
        selector: "node[group='usecase']",
        style: {{ "background-color": "#5c6bc0", "border-color": "#5c6bc0" }}
      }},
      {{
        selector: "node[group='rfc']",
        style: {{ "background-color": "#66bb6a", "border-color": "#66bb6a" }}
      }},
      {{
        selector: "node[group='impl']",
        style: {{ "background-color": "#ff9800", "border-color": "#ff9800" }}
      }},
      {{
        selector: "edge",
        style: {{
          "line-color": "rgba(171,71,188,0.1)",
          "width": 1,
          "curve-style": "bezier",
        }}
      }},
      {{
        selector: "node:active",
        style: {{ "overlay-opacity": 0 }}
      }},
      {{
        selector: ".highlighted",
        style: {{ "background-opacity": 0.4, "border-width": 3 }}
      }},
      {{
        selector: ".highlighted-edge",
        style: {{ "line-color": "rgba(171,71,188,0.5)", "width": 2 }}
      }},
      {{
        selector: ".dimmed",
        style: {{ "opacity": 0.08 }}
      }},
      {{
        selector: ".hidden",
        style: {{ "display": "none" }}
      }},
    ],
    layout: {{
      name: "cose",
      animate: false,
      nodeDimensionsIncludeLabels: true,
      nodeRepulsion: function() {{ return 8000; }},
      idealEdgeLength: function() {{ return 100; }},
      edgeElasticity: function() {{ return 100; }},
      gravity: 0.3,
      numIter: 500,
      padding: 40,
    }},
    minZoom: 0.2,
    maxZoom: 4,
    wheelSensitivity: 0.3,
  }});

  // Hover highlight
  cy.on("mouseover", "node", function(e) {{
    const node = e.target;
    const neighborhood = node.neighborhood().add(node);
    cy.elements().addClass("dimmed");
    neighborhood.removeClass("dimmed");
    node.addClass("highlighted");
    node.connectedEdges().addClass("highlighted-edge");
  }});

  cy.on("mouseout", "node", function() {{
    cy.elements().removeClass("dimmed highlighted highlighted-edge");
  }});

  // Click navigate
  cy.on("tap", "node", function(e) {{
    const url = e.target.data("url");
    if (url) {{
      const base = window.location.pathname.replace(/knowledge-graph\\/?$/, "");
      window.location.href = base + url;
    }}
  }});

  // Cursor
  cy.on("mouseover", "node", function() {{ document.body.style.cursor = "pointer"; }});
  cy.on("mouseout", "node", function() {{ document.body.style.cursor = "default"; }});

  // Build filter buttons
  const filterDiv = document.getElementById("filters");
  if (filterDiv) {{
    Object.entries(GROUP_NAMES).forEach(([key, label]) => {{
      const btn = document.createElement("button");
      btn.textContent = label;
      btn.className = "active";
      btn.dataset.group = key;
      btn.style.borderColor = GROUP_COLORS[key];
      btn.style.color = GROUP_COLORS[key];
      btn.onclick = function() {{
        if (activeGroups.has(key)) {{
          activeGroups.delete(key);
          btn.classList.remove("active");
          btn.classList.add("off");
        }} else {{
          activeGroups.add(key);
          btn.classList.add("active");
          btn.classList.remove("off");
        }}
        cy.nodes().forEach(n => {{
          if (activeGroups.has(n.data("group"))) n.removeClass("hidden");
          else n.addClass("hidden");
        }});
        cy.edges().forEach(edge => {{
          const sg = edge.source().data("group");
          const tg = edge.target().data("group");
          if (activeGroups.has(sg) && activeGroups.has(tg)) edge.removeClass("hidden");
          else edge.addClass("hidden");
        }});
      }};
      filterDiv.appendChild(btn);
    }});
  }}
}}

// Run immediately (SPA navigation) or on DOMContentLoaded (full page load)
if (document.readyState === "loading") {{
  document.addEventListener("DOMContentLoaded", initKnowledgeGraph);
}} else {{
  initKnowledgeGraph();
}}

window.toggleFS = function() {{
  const c = document.getElementById("graph-container");
  if (!document.fullscreenElement) {{
    c.requestFullscreen().then(() => window._graphCy && window._graphCy.resize()).catch(() => {{}});
  }} else {{
    document.exitFullscreen();
  }}
}};
document.addEventListener("fullscreenchange", () => {{
  const btn = document.getElementById("fs-btn");
  if (btn) btn.textContent = document.fullscreenElement ? "Exit" : "Fullscreen";
  if (window._graphCy) setTimeout(() => window._graphCy.resize(), 100);
}});
}})();
"""

    js_path = os.path.join(docs_dir, "assets", "javascripts", "knowledge-graph.js")
    os.makedirs(os.path.dirname(js_path), exist_ok=True)

    existing = ""
    if os.path.exists(js_path):
        with open(js_path, "r", encoding="utf-8") as f:
            existing = f.read()

    if existing != js_content:
        with open(js_path, "w", encoding="utf-8") as f:
            f.write(js_content)
        log.info(f"Knowledge graph updated: {node_count} nodes, {edge_count} edges")
    else:
        log.info(f"Knowledge graph unchanged: {node_count} nodes, {edge_count} edges")
